language: node_js
node_js:
  - lts/*

before_install:
  - npm i -g gulp-cli
install:
  - cd ./app
  - npm install
  - cd ./../
  - npm install

stages:
  - lint
  - build
  - deploy

jobs:
  include:
    - stage: lint
      script:
        - gulp lint
    - stage: build
      script:
        - gulp build
      skip_cleanup: true
    - stage: build
      on:
        branch: master
      script:
        - gulp -f devSetup.gulpfile.js
        - gulp packages
      skip_cleanup: true
    # Github Releases
    - stage: deploy
      deploy:
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file_glob: true
          # see at gulpfile.js > zipPackages
          file: ./build/ctjs - $TRAVIS_TAG/ct.js $TRAVIS_TAG for *.zip
          skip_cleanup: true
          draft: true
          on:
            tags: true
            branch: master
    # Push to comigo.itch.io/ct
    - stage: deploy
      deploy:
        - provider: script
          script: gulp deployOnly
          skip_cleanup: true
          on:
            branch: master